annotations:
  category: Database
apiVersion: v1
home: https://github.com/promzeus/RedisOperator-haproxy-failover
maintainers:
  - name: Dmytro Onyshko
    email: promzeus@gmail.com
appVersion: 0.0.1
description: redisoperator-ha-failover
name: redis-failover
version: 0.0.1