apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template ".fullname" . }}-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template ".fullname" . }}
data:
{{ if .Values.haproxy.enabled }}
  haproxy.cfg: |
{{- include "config-haproxy.cfg" . }}
{{- end }}

