apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: {{ template ".fullname" . }}-node
spec:
{{- if .Values.sentinel.enabled }}
  sentinel:
    replicas: {{ .Values.sentinel.replicas }}
{{- if .Values.sentinel.nodeSelector }}
    nodeSelector: {{- toYaml .Values.sentinel.nodeSelector | nindent 6 }}
{{- end }}
    tolerations:
      - effect: NoSchedule
        operator: Exists
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
{{- end }}
  redis:
    replicas: {{ .Values.redis.replicas }}
    customConfig:
      - "maxclients 5000"
      - "hz 50"
      - "tcp-keepalive 300"
      - "client-output-buffer-limit normal 0 0 0"
      - "client-output-buffer-limit slave 2147483648 2147483648 0"
      - "client-output-buffer-limit pubsub 33554432 8388608 60"
# - "appendonly yes"
# - "save "
{{- if .Values.redis.nodeSelector }}
    nodeSelector: {{- toYaml .Values.redis.nodeSelector | nindent 6 }}
{{- end }}
    tolerations:
      - effect: NoSchedule
        operator: Exists
    exporter:
      enabled: true
      image: docker.io/bitnami/redis-exporter:1.12.1-debian-10-r11
      args:
        - redis_exporter
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: redis
                app.kubernetes.io/managed-by: redis-operator
                app.kubernetes.io/name: {{ template ".fullname" . }}-node
                app.kubernetes.io/part-of: redis-failover
                redisfailovers.databases.spotahome.com/name: {{ template ".fullname" . }}-node
            topologyKey: kubernetes.io/hostname
    storage:
      persistentVolumeClaim:
        metadata:
          name: {{ template ".fullname" . }}-persistent-data
        spec:
          accessModes:
            - {{ .Values.redis.persistent.accessModes }}
          resources:
            requests:
              storage: {{ .Values.redis.persistent.storage }}