apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: {{ template "redis.fullname" . }}-node
spec:
{{- if .Values.sentinel.enabled }}
  sentinel:
    replicas: {{ .Values.sentinel.replicas }}
{{- if .Values.nodeSelector }}
    nodeSelector: {{- toYaml .Values.nodeSelector | nindent 6 }}
{{- end }}
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
{{- end }}
  redis:
    replicas: {{ .Values.redis.replicas }}
{{- if .Values.nodeSelector }}
    nodeSelector: {{- toYaml .Values.nodeSelector | nindent 6 }}
{{- end }}
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
{{- if .Values.redis.persistent }}
    storage:
      persistentVolumeClaim:
        metadata:
          name: {{ template "redis.fullname" . }}-persistent-data
        spec:
          accessModes:
            - {{ .Values.redis.persistent.accessModes }}
          resources:
            requests:
              storage: {{ .Values.redis.persistent.storage }}
{{- end}}