{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template ".serviceAccountName" . }}
  labels:
    app: {{ template ".fullname" . }}
    chart: {{ template ".chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
